
### For OpenAI
#OPENAI_API_KEY: sk-proj-Qb3arpbATMAXg1GF8iR0T3BlbkFJtoOdAQ2VyiCh7ugfchIE
#OPENAI_API_BASE: https://api.openai-proxy.org/v1

### For Azure OpenAI
API_VERSION: 
AZURE_OPENAI_API_KEY:
AZURE_OPENAI_API_BASE: 


### For VLLM
#OPENAI_API_BASE: http://localhost:8000/v1
#OPENAI_API_KEY: 1234

